name: Keith Reilly
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c57383c5-6455-4d47-98a0-4deff66db671.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9ad91bf4-f4a6-4751-975d-ae198fcefc8e.jpg
layout_spectrum: 0.4866783141624182
typography_spectrum: 0.5562684389296919
analytics: {}
opengraph:
  type: kreilly1
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/416f83af-d6d2-48f7-bd64-4a2339c9cf05.jpg
color:
  brandColors:
    - '#354242'
    - '#ACEBAE'
    - '#FFFF9D'
    - '#C9DE55'
    - '#7D9100'
  brandStrength: 0.9751915538160111
  lightness: 0.8837387859550628
  saturation: 0.2247130510454795
  rhythmicContrast: 0.5206413815078887
purpose:
  - type: contact
    label: Contact me!!!
    url: 'mailto:Keith@KeithReilly.com'
  - type: contact
    label: Call 2017882368
    url: 'tel:2017882368'
title: My Life
description: Pictures and posts from my Life!
author:
  name: Keith Reilly
  url: 'http://www.keithreilly.com'
  email: keith@keithreilly.com
content_rating:
  adult: false
navigation:
  - name: About US!
    id: b2f67764-845d-453d-bfd3-5bb75dacbee7
    type: content
content: []
github: true
